version: '3'

services:
  song-service:
    image: 'song-service:latest'
    container_name: 'song-service-container'
    ports:
      - '8080:8080'
    depends_on:
      - song-db
    env_file:
      - song-service/.env

  song-db:
    image: 'postgres:13'
    container_name: song-db
    ports:
      - '5432:5432'
    env_file:
      - song-service/.env

  resource-service:
    image: 'resource-service:latest'
    container_name: 'resource-service-container'
    ports:
      - '8081:8081'
    depends_on:
      - resource-db
      - song-service
    env_file:
      - resource-service/.env

  resource-db:
    image: 'postgres:13'
    container_name: resource-db
    ports:
      - '5433:5432'
    env_file:
      - resource-service/.env