version: '3'

services:
  service-discovery:
    build:
      context: service-discovery
    image: 'service-discovery:latest'
    container_name: 'service-discovery'
    ports:
      - '8761:8761'
    env_file:
      - service-discovery/.env


  gateway-service:
    build:
      context: gateway-service
    image: 'gateway-service:latest'
    container_name: 'gateway-service'
    depends_on:
      - service-discovery
    ports:
      - '8090:8090'
    env_file:
      - gateway-service/.env


  song-service:
    image: 'song-service:latest'
    container_name: 'song-service-container'
    build:
      context: song-service
    #    deploy:
    #      mode: replicated
    #      replicas: 2
    ports:
      - '8080:8080'
    #        '8070-8071:8080'
    depends_on:
      - song-db
      - service-discovery
      - gateway-service
    env_file:
      - song-service/.env

  song-db:
    image: 'postgres:13'
    container_name: song-db
    ports:
      - '5432:5432'
    env_file:
      - song-service/.env
    volumes:
      - ./song-service/song-init.sql:/docker-entrypoint-initdb.d/song-init.sql


  resource-service:
    image: 'resource-service:latest'
    container_name: 'resource-service-container'
    build:
      context: resource-service
    ports:
      - '8081:8080'
    depends_on:
      - resource-db
      - song-service
      - service-discovery
      - gateway-service
    env_file:
      - resource-service/.env

  resource-db:
    image: 'postgres:13'
    container_name: resource-db
    ports:
      - '5433:5432'
    env_file:
      - resource-service/.env
    volumes:
      - ./resource-service/resource-init.sql:/docker-entrypoint-initdb.d/resource-init.sql