version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
      - '8070:8070'
    environment:
      - SERVICES=s3:4566
      - HOSTNAME_EXTERNAL=localhost
      - DEBUG=1
      - PORT_WEB_UI=8070
      - AWS_DEFAULT_REGION=eu-central-1
      - AWS_SECRET_ACCESS_KEY=secret-key
      - AWS_ACCESS_KEY=access-key